name: JoinsPlus
version: 0
author: moderator_man
main: com.oldschoolminecraft.jp.JoinsPlus
commands:
    cjm:
        description: Manage your custom join message.
        usage: /cjm [sudo [player]] <message>
        default: op